# docker-compose.yml

services:
  db:
    image: postgres:17.0
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'
    networks:
      - nestjs-boilerplate-network

  redis:
    image: redis:latest
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
    networks:
      - nestjs-boilerplate-network

  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - nestjs-boilerplate-network

  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - '${PORT}:3000'
  #   depends_on:
  #     - db
  #     - redis
  #   networks:
  #     - nestjs-boilerplate-network

volumes:
  postgres:

networks:
  nestjs-boilerplate-network:
    driver: bridge
